export default {
 Title: require('../assets/images/Title.png'),
 ScoopIce:require('../assets/images/scoopIce.png'),
 IceCake:require('../assets/images/icecake.png'),
 LoginPic:require('../assets/images/loginPic.png'),
 Hide:require('../assets/images/Hide.png'),
 View:require('../assets/images/View.png'),
 Twitter:require('../assets/images/twitter.png'),
 Facebook:require('../assets/images/facebook.png'),
 Google:require('../assets/images/google.png'),
 cart:require('../assets/images/Bag.png'),
 menu:require('../assets/images/menu.png'),
 BananaImg:require('../assets/images/banana.png'),
 filter:require('../assets/images/Filter.png'),
 image:require('../assets/images/image.png'),
 Rating:require('../assets/images/Rating.png'),
};
