export default {
  icHide: require('../assets/images/visibilityoff.png'),
  icView: require('../assets/images/eyevisible.png'),
  icFACEBOOK: require('../assets/images/facebookicon.png'),
  icINSTAGRAM: require('../assets/images/instagramicon.png'),
  icGOOGLE: require('../assets/images/googleicon.png'),
  icARROWBACK: require('../assets/images/arrowBack.png'),
  icLOCATIONICON: require('../assets/images/LocationIcon.png'),
  icDOWNARROW: require('../assets/images/down.png'),
  icFILTER: require('../assets/images/filter.png'),
  icIMAGE1: require('../assets/images/Image1.png'),
  icIMAGE2: require('../assets/images/Image2.png'),
  icIMAGE3: require('../assets/images/Image3.png'),
  icSREACHICON: require('../assets/images/sreachIcon.png'),
  icLOCATIONARROW: require('../assets/images/locationArrow.png'),
  icLEFTARROW: require('../assets/images/left-arrow.png'),
  icSTAR: require('../assets/images/Star.png'),
  icCART: require('../assets/images/cart.png'),
  icTREE_LOUNGE: require('../assets/images/tresslounge.png'),
  icMENUICON: require('../assets/images/menuIcon.png'),
  icWAXINGCOMBO: require('../assets/images/waxingxCombo.png'),
  icFACEPACKCOMBO: require('../assets/images/facePackCombo.png'),
  icSUMMERCOMBO: require('../assets/images/SummerCombo.png'),
  icPARTYREDAYCOMBO: require('../assets/images/PartyReadyCombo.png'),
};
